In [3]:
import numpy as np

In [221]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Q = givens_qr(A_mat)

In [220]:
R = A_mat
R

array([[  1.13385581e+00,   3.60998282e-01,   2.95099251e+00,
         -1.01071052e+00],
       [  9.06184956e-18,   6.40531217e-01,   4.28857747e-01,
         -1.36816497e-01],
       [  1.06905726e-17,   3.71148918e-19,   1.08079798e+00,
         -2.01973547e+00],
       [  1.18171366e-17,  -3.06702012e-18,  -6.32942778e-18,
          4.52232385e-01]])

In [222]:
np.dot(Q, R)

array([[  3.40000000e-01,   3.62460958e-01,   1.93490208e+00,
         -1.86590376e+00],
       [ -1.08167879e+00,  -2.37657607e-01,  -2.66589287e+00,
          4.01792612e-01],
       [ -9.94765808e-19,  -1.48935380e-01,   4.67178599e-01,
         -1.19959518e+00],
       [ -1.13568225e-17,  -5.58644875e-01,  -6.32159144e-01,
          5.67248666e-01]])

In [195]:
np.dot(Q,R)

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])

In [142]:
import numpy.linalg as nla

In [143]:
nla.cond(A)

37.75729255859725

In [177]:
Q, R = nla.qr(A_mat)

In [440]:
np.dot(Q,R)

array([[ -6.20988618e-01,   1.55876963e-01,  -1.47162690e+00,
          2.03497762e+00],
       [ -9.48684424e-01,   6.82240414e-01,   2.97991851e+00,
         -6.26971769e-01],
       [ -2.96008167e-18,  -2.61414255e-02,  -3.28482050e-02,
         -8.43637536e-01],
       [  1.40823581e-17,   2.79826130e-01,   3.05136730e+00,
         -1.66351376e+00]])

In [486]:
def givens_qr(A):
    m,n = A.shape
    Q = np.eye(m)
    R = A
    for c in xrange(n):
        for r in reversed(xrange(c+1, m)):  # m-1, m-2, ... c+2, c+1
            # in this row and the previous row, use zeroing givens to
            # place a zero in the lower row
            coeffs = zeroing_givens_coeffs(R[r-1, c], R[r,c])
            left_givensT(coeffs, R[:, c:], r-1, r) 
            # left_givensT(coeffs, A[r-1:r+1, c:], 0, 1)
            left_givensT(coeffs, Q[:, c:], r-1, r)
    return Q,R


In [487]:
# GvL, pg. 216 .... Section 5.1.9
def left_givensT((c,s), A, r1, r2):
    ''' update A <- G.T.dot(A) ... affects rows r1 and r2 '''
    givensT = np.array([[ c, -s],   # manually transposed 
                        [ s,  c]])
    A[[r1,r2],:] = np.dot(givensT, A[[r1,r2],:])

# A.dot(G) .... affects two cols of A
def right_givens((c,s), A, c1, c2):
    ''' update A <- A.dot(G) ... affects cols c1 and c2 '''
    givens = np.array([[ c, s],
                       [-s, c]])
    A[:,[c1, c2]] = np.dot(A[:,[c1, c2]], givens)

In [488]:
def zeroing_givens_coeffs(x,z):
    ''' for the values x,z compute cos th, sin th 
        s.t. applying a Givens rotation G(cos th,sin th) 
             on 2 rows(or cols) with values x,z will
             maps x --> r and z --> 0'''
    if z == 0.0: # better:  abs(z) < np.finfo(np.double).eps
        return 1.0,0.0
    r = np.hypot(x,z) # C99 hypot is safe for under/overflow
    return x/r, -z/r

In [494]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
A = np.arange(1.0, 10.0).reshape(3,3)
print A
Q,R = givens_qr(A)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [498]:
R

array([[  8.12403840e+00,   9.60113630e+00,   1.10782342e+01],
       [ -1.74738667e-17,   9.04534034e-01,   1.80906807e+00],
       [ -1.11022302e-16,  -2.10803855e-17,  -4.21607710e-17]])

In [496]:
np.dot(Q, R)

array([[  1.00000000e+00,   1.62717995e+00,   2.25435991e+00],
       [ -8.06225775e+00,  -9.25539552e+00,  -1.04485333e+01],
       [  3.10573127e-17,   7.38548946e-01,   1.47709789e+00]])

In [483]:
B

array([[  1.13385581e+00,   3.60998282e-01,   2.95099251e+00,
         -1.01071052e+00],
       [  9.06184956e-18,   6.40531217e-01,   4.28857747e-01,
         -1.36816497e-01],
       [  1.06905726e-17,   3.71148918e-19,   1.08079798e+00,
         -2.01973547e+00],
       [  1.18171366e-17,  -3.06702012e-18,  -6.32942778e-18,
          4.52232385e-01]])

In [454]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Q, R = givens_qr(A_mat)

In [455]:
A_mat

array([[  1.13385581e+00,   3.60998282e-01,   2.95099251e+00,
         -1.01071052e+00],
       [  9.06184956e-18,   6.40531217e-01,   4.28857747e-01,
         -1.36816497e-01],
       [  1.06905726e-17,   3.71148918e-19,   1.08079798e+00,
         -2.01973547e+00],
       [  1.18171366e-17,  -3.06702012e-18,  -6.32942778e-18,
          4.52232385e-01]])

In [456]:
np.dot(Q,R)

array([[  3.40000000e-01,   3.62460958e-01,   1.93490208e+00,
         -1.86590376e+00],
       [ -1.08167879e+00,  -2.37657607e-01,  -2.66589287e+00,
          4.01792612e-01],
       [ -9.94765808e-19,  -1.48935380e-01,   4.67178599e-01,
         -1.19959518e+00],
       [ -1.13568225e-17,  -5.58644875e-01,  -6.32159144e-01,
          5.67248666e-01]])

In [458]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
A_mat

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])

In [151]:
SSS.givens_QR(A)

(array([[  1.00000000e+00,   0.00000000e+00,  -4.92581904e-35,
          -2.73012869e-34],
        [ -2.77420973e-34,   1.00000000e+00,   2.67306193e-18,
           1.92592994e-34],
        [  0.00000000e+00,  -4.74622348e-19,   1.00000000e+00,
           1.50898596e-17],
        [  0.00000000e+00,   2.63058809e-18,  -3.99802671e-17,
           1.00000000e+00]]),
 array([[  1.13385581e+00,   3.60998282e-01,   2.95099251e+00,
          -1.01071052e+00],
        [  0.00000000e+00,   6.40531217e-01,   4.28857747e-01,
          -1.36816497e-01],
        [  0.00000000e+00,  -5.27084008e-36,   1.08079798e+00,
          -2.01973547e+00],
        [  1.76111171e-51,   0.00000000e+00,   3.35679185e-17,
           4.52232385e-01]]))

(4, 4)

# Householder transformation

In [307]:
def Householder(A):
    m,n = A.shape
    R = A
    Q = np.eye(m)
    
    for j in range(n):
        print(j)
        norm_x = nla.norm(R[j:n,j])
        s = -np.sign(R[j,j])
        u1 = R[j,j] - s*norm_x
        w = R[j:n,j]/norm_x
        w[1] = 1
        alpha = (-s *u1)/norm_x
        R[j:m,j:n] = R[j:m,j:n] - 2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:m,j:n])))
        Q[:,j:n] = Q[:,j:n] - (Q[:,j:n]*w)*(alpha*w)
        
    return(Q,R)
    
    
        

In [308]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Householder(A_mat)

0


ValueError: shapes (3,) and (4,4) not aligned: 3 (dim 0) != 4 (dim 0)

In [429]:
def Householder(A):
    m,n = A.shape
    R = A
    Q = np.eye(m)
    reflecMat = []
    for j in range(n):
        #print(j)
        x = R[j:m,j]
        e_1 = np.zeros(len(x))
        e_1[0] = 1
        v_k = np.sign(x[0])*nla.norm(x)*e_1+x
        v_k = v_k/nla.norm(v_k)
        print(v_k)
        reflecMat.append(v_k)
        R[j:m,j:n] = R[j:m,j:n] - 2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:m,j:n])))
        
        #Q[n-j-1:m,] = Q[n-j-1:m,] - 2*np.dot(v_k,np.outer(np.transpose(v_k),Q[n-j-1:m,]))
    #print(reflecMat)
    
    for k in range(n-1,-1,-1):
        Q[k:m,] = Q[k:m,] - 2*np.outer(reflecMat[k],np.dot(np.transpose(reflecMat[k]),Q[k:m,]))
    return(Q,R)
    

In [430]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Q,R=Householder(A)
print Q,R

[ 0.80618291  0.24614505  0.50487084  0.18597626]
[ 0.71678326 -0.14873391 -0.68124884]
[ 0.99295432 -0.11849775]
[ 1.]
[[-0.29986176 -0.45548197  0.72189882  0.4260061 ]
 [-0.39687586 -0.16662497  0.24300203 -0.86929609]
 [-0.81403649 -0.07202495 -0.52451613  0.23883014]
 [-0.29986176  0.87154157  0.38038788  0.07617926]] [[ -1.13385581e+00  -3.60998282e-01  -2.95099251e+00   1.01071052e+00]
 [  5.55111512e-17  -6.40531217e-01  -4.28857747e-01   1.36816497e-01]
 [  1.11022302e-16  -2.77555756e-17  -1.08079798e+00   2.01973547e+00]
 [  5.55111512e-17  -2.22044605e-16  -5.55111512e-17  -4.52232385e-01]]


In [431]:
np.dot(Q,R)

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])

In [432]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
nla.cond(A)

37.757292558597278

In [433]:
nla.cond(R)

37.757292558597285

In [434]:
m,n = A.shape
R = A
Q = np.eye(m)
reflecMat = []
for j in range(n):
    print(j)
    x = R[j:m,j]
    e_1 = np.zeros(len(x))
    e_1 = 1
    v_k = np.sign(x[0])*nla.norm(x)*e_1+x
    v_k = v_k/nla.norm(v_k)
    #print(v_k)
    reflecMat.append(v_k)
    R[j:m,j:n] = R[j:m,j:n] - 2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:m,j:n])))
    print(R)
    Q[k:,] = Q[k:,] - 2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:m,j:n])))
        
    #Q[n-j-1:m,] = Q[n-j-1:m,] - 2*np.dot(v_k,np.outer(np.transpose(v_k),Q[n-j-1:m,]))
    #print(reflecMat)
    
for k in range(n-1,-1,-1):
    Q[k:m,] = Q[k:m,] - 2*np.outer(reflecMat[k],np.dot(np.transpose(reflecMat[k]),Q[k:m,]))
    

0
[[-0.62098862  0.12830616 -1.91064296  1.23191658]
 [-0.5827112  -0.04197148 -1.39563245  0.8166889 ]
 [-0.41811832 -0.03916535 -0.08508728 -1.53679014]
 [-0.62098862 -0.72169384 -2.11064296  0.88191658]]
1
[[-0.62098862  0.12830616 -1.91064296  1.23191658]
 [-0.5827112   0.47760356  0.57161228  0.474629  ]
 [-0.41811832  0.47850617  1.87495021 -1.87759686]
 [-0.62098862  0.25896759  1.6023934   0.23630252]]


ValueError: operands could not be broadcast together with shapes (4,4) (3,3) 

In [397]:
np.dot(Q,R)

array([[ 0.56692079,  0.23670362, -1.89392101,  0.45255037],
       [ 0.18896823,  0.32798471, -1.52529454, -1.31892664],
       [ 0.1889899 ,  0.32799351,  2.03596316, -1.6293502 ],
       [-0.94488287, -0.51905461,  0.04235322,  0.85143913]])

In [412]:
j = 1
x = R[j:m,j]
e_1 = np.zeros(len(x))
e_1 = 1
v_k = np.sign(x[0])*nla.norm(x)*e_1+x
v_k = v_k/nla.norm(v_k)
#print(v_k)
reflecMat.append(v_k)
R[j:m,j:n] = R[j:m,j:n] - 2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:m,j:n])))
R

array([[ 0.5460385 , -0.5551099 ,  0.57146275,  1.3890673 ],
       [ 0.55886022,  0.2794929 ,  0.4610446 ,  1.50331191],
       [ 0.61399362,  0.28081781,  2.01933154,  0.50286073],
       [ 0.5460385 ,  0.27473272,  2.33314559,  0.93902951]])

In [413]:
R[j:m,j]

array([ 0.2794929 ,  0.28081781,  0.27473272])

In [336]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
m,n = A.shape
R = A
Q = np.eye(m)
j = 1

In [337]:
x = R[j:m,j]
e_1 = np.zeros(len(x))
e_1 = 1
v_k = np.sign(x[0])*nla.norm(x)*e_1+x
v_k = v_k/nla.norm(v_k)
R[j:m,j:n] = R[j:m,j:n] - 2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:m,j:n])))
Q[n-j-1:m,] = Q[n-j-1:m,] - 2*np.dot(v_k,np.outer(np.transpose(v_k),Q[n-j-1:m,]))

ValueError: operands could not be broadcast together with shapes (2,4) (8,) 

In [339]:
2*np.dot(v_k,np.outer(np.transpose(v_k),Q[n-j-1:m,]))

array([ 0.,  0.,  2.,  0.,  0.,  0.,  0.,  2.])

ValueError: shapes (3,) and (2,4) not aligned: 3 (dim 0) != 2 (dim 0)

In [326]:
v_k

array([-0.51715656, -0.50587612, -0.45737023, -0.51715656])

In [296]:
(Q[:,j:n]*w)*(alpha*w)

array([[ 0.,  0.,  0.],
       [-2.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0.,  0.]])

In [299]:
(alpha*w)

array([ 2.,  2.,  0.])

In [285]:
2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:m,j:n])))

array([[ 0.4776352 ,  3.82241798, -1.45576494],
       [ 0.52722084,  4.21924179, -1.60689498],
       [ 0.09196916,  0.7360106 , -0.28030907]])

In [280]:
v_k.dot(np.dot(np.transpose(v_k),R[j:m,j:n]))

2.2082839624843231

In [383]:
range(5,0,-1)

[5, 4, 3, 2, 1]

In [425]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
m,n = A.shape
R = A
Q = np.eye(m)
reflecMat = []
for j in range(n):
    print(j)
    x = R[j:,j]
    e_1 = np.zeros(len(x))
    e_1 = 1
    v_k = np.sign(x[0])*nla.norm(x)*e_1+x
    v_k = v_k/nla.norm(v_k)
    R[j:,j] = R[j:,j] - np.transpose(2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:,j]))))
    Q[j:,] = Q[j:,] - 2*np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),Q[j:,])))

0
1
2
3


In [426]:
R[j:,j] - np.transpose(np.outer(v_k,np.transpose(np.dot(np.transpose(v_k),R[j:,j]))))

array([[ 0.]])

In [427]:
Q

array([[ 0.60802985, -0.42122452, -0.54701829, -0.39197015],
       [ 0.55462467,  0.70929065, -0.20477091,  0.38388426],
       [-0.14018105,  0.55479145,  0.00460978, -0.82008199],
       [ 0.5504911 , -0.10808851,  0.81167642, -0.16265855]])

In [428]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
nla.qr(A)

(array([[-0.29986176, -0.45548197,  0.72189882, -0.4260061 ],
        [-0.39687586, -0.16662497,  0.24300203,  0.86929609],
        [-0.81403649, -0.07202495, -0.52451613, -0.23883014],
        [-0.29986176,  0.87154157,  0.38038788, -0.07617926]]),
 array([[-1.13385581, -0.36099828, -2.95099251,  1.01071052],
        [ 0.        , -0.64053122, -0.42885775,  0.1368165 ],
        [ 0.        ,  0.        , -1.08079798,  2.01973547],
        [ 0.        ,  0.        ,  0.        ,  0.45223238]]))