In [10]:
import numpy as np

In [11]:
def givens_qr(A):
    m,n = A.shape
    Q = np.eye(m)
    R = A
    for c in xrange(n):
        for r in reversed(xrange(c+1, m)):  # m-1, m-2, ... c+2, c+1
            # in this row and the previous row, use zeroing givens to
            # place a zero in the lower row
            coeffs = zeroing_givens_coeffs(R[r-1, c], R[r,c])
            left_givensT(coeffs, R[:, c:], r-1, r) 
            # left_givensT(coeffs, A[r-1:r+1, c:], 0, 1)
            left_givensT(coeffs, Q[:, c:], r-1, r)
    return Q,R

In [12]:
# GvL, pg. 216 .... Section 5.1.9
def left_givensT((c,s), A, r1, r2):
    ''' update A <- G.T.dot(A) ... affects rows r1 and r2 '''
    givensT = np.array([[ c, -s],   # manually transposed 
                        [ s,  c]])
    A[[r1,r2],:] = np.dot(givensT, A[[r1,r2],:])

# A.dot(G) .... affects two cols of A
def right_givens((c,s), A, c1, c2):
    ''' update A <- A.dot(G) ... affects cols c1 and c2 '''
    givens = np.array([[ c, s],
                       [-s, c]])
    A[:,[c1, c2]] = np.dot(A[:,[c1, c2]], givens)

In [13]:
def zeroing_givens_coeffs(x,z):
    ''' for the values x,z compute cos th, sin th 
        s.t. applying a Givens rotation G(cos th,sin th) 
             on 2 rows(or cols) with values x,z will
             maps x --> r and z --> 0'''
    if z == 0.0: # better:  abs(z) < np.finfo(np.double).eps
        return 1.0,0.0
    r = np.hypot(x,z) # C99 hypot is safe for under/overflow
    return x/r, -z/r

In [14]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Q = givens_qr(A_mat)

In [15]:
R = A_mat
R

array([[ 1.13385581e+00,  3.60998282e-01,  2.95099251e+00,
        -1.01071052e+00],
       [ 9.06184956e-18,  6.40531217e-01,  4.28857747e-01,
        -1.36816497e-01],
       [ 1.06905726e-17,  3.71148918e-19,  1.08079798e+00,
        -2.01973547e+00],
       [ 1.18171366e-17, -3.06702012e-18, -6.32942778e-18,
         4.52232385e-01]])

In [16]:
np.dot(Q, R)

array([[[ 3.40000000e-01,  3.62460958e-01,  1.93490208e+00,
         -1.86590376e+00],
        [-1.08167879e+00, -2.37657607e-01, -2.66589287e+00,
          4.01792612e-01],
        [-9.94765808e-19, -1.48935380e-01,  4.67178599e-01,
         -1.19959518e+00],
        [-1.13568225e-17, -5.58644875e-01, -6.32159144e-01,
          5.67248666e-01]],

       [[ 1.28562900e+00,  6.40550669e-01,  6.69024364e+00,
         -7.61269077e+00],
        [ 1.90471839e-17,  4.10280240e-01,  7.38205361e-01,
         -1.01568729e+00],
        [-1.91572912e-19,  1.06927171e-17,  1.16812427e+00,
         -3.09631579e+00],
        [ 1.87430209e-17,  9.14438062e-19,  2.38537613e-17,
          2.04514130e-01]]])

In [17]:
np.dot(Q,R)

array([[[ 3.40000000e-01,  3.62460958e-01,  1.93490208e+00,
         -1.86590376e+00],
        [-1.08167879e+00, -2.37657607e-01, -2.66589287e+00,
          4.01792612e-01],
        [-9.94765808e-19, -1.48935380e-01,  4.67178599e-01,
         -1.19959518e+00],
        [-1.13568225e-17, -5.58644875e-01, -6.32159144e-01,
          5.67248666e-01]],

       [[ 1.28562900e+00,  6.40550669e-01,  6.69024364e+00,
         -7.61269077e+00],
        [ 1.90471839e-17,  4.10280240e-01,  7.38205361e-01,
         -1.01568729e+00],
        [-1.91572912e-19,  1.06927171e-17,  1.16812427e+00,
         -3.09631579e+00],
        [ 1.87430209e-17,  9.14438062e-19,  2.38537613e-17,
          2.04514130e-01]]])

In [18]:
import numpy.linalg as nla

In [20]:
nla.cond(A_mat)

37.75729255859725

In [21]:
Q, R = nla.qr(A_mat)

In [22]:
np.dot(Q,R)

array([[ 1.13385581e+00,  3.60998282e-01,  2.95099251e+00,
        -1.01071052e+00],
       [ 9.06184956e-18,  6.40531217e-01,  4.28857747e-01,
        -1.36816497e-01],
       [ 1.06905726e-17,  3.71148918e-19,  1.08079798e+00,
        -2.01973547e+00],
       [ 1.18171366e-17, -3.06702012e-18, -6.32942778e-18,
         4.52232385e-01]])

In [23]:
A = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
A = np.arange(1.0, 10.0).reshape(3,3)
print A
Q,R = givens_qr(A)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [24]:
R

array([[ 8.12403840e+00,  9.60113630e+00,  1.10782342e+01],
       [-1.74738667e-17,  9.04534034e-01,  1.80906807e+00],
       [-1.11022302e-16, -2.10803855e-17, -4.21607710e-17]])

In [25]:
np.dot(Q, R)

array([[ 1.00000000e+00,  1.62717995e+00,  2.25435991e+00],
       [-8.06225775e+00, -9.25539552e+00, -1.04485333e+01],
       [ 3.10573127e-17,  7.38548946e-01,  1.47709789e+00]])

In [27]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
Q, R = givens_qr(A_mat)

In [28]:
A_mat

array([[ 1.13385581e+00,  3.60998282e-01,  2.95099251e+00,
        -1.01071052e+00],
       [ 9.06184956e-18,  6.40531217e-01,  4.28857747e-01,
        -1.36816497e-01],
       [ 1.06905726e-17,  3.71148918e-19,  1.08079798e+00,
        -2.01973547e+00],
       [ 1.18171366e-17, -3.06702012e-18, -6.32942778e-18,
         4.52232385e-01]])

In [29]:
np.dot(Q,R)

array([[ 3.40000000e-01,  3.62460958e-01,  1.93490208e+00,
        -1.86590376e+00],
       [-1.08167879e+00, -2.37657607e-01, -2.66589287e+00,
         4.01792612e-01],
       [-9.94765808e-19, -1.48935380e-01,  4.67178599e-01,
        -1.19959518e+00],
       [-1.13568225e-17, -5.58644875e-01, -6.32159144e-01,
         5.67248666e-01]])

In [30]:
A_mat = np.array([[0.34,0.4,0.3,0.9],[0.45,0.25,0.98,0.46],[0.923,0.34,3,-2],[0.34,-0.45,0.1,0.55]])
A_mat

array([[ 0.34 ,  0.4  ,  0.3  ,  0.9  ],
       [ 0.45 ,  0.25 ,  0.98 ,  0.46 ],
       [ 0.923,  0.34 ,  3.   , -2.   ],
       [ 0.34 , -0.45 ,  0.1  ,  0.55 ]])