# Matrix Norm

In [1]:
import numpy as np

In [2]:
 b = np.array([[2,3,4],[5,7,9],[3,5,2]])

In [3]:
b

array([[2, 3, 4],
       [5, 7, 9],
       [3, 5, 2]])

In [4]:
np.linalg.norm(b,ord=np.inf)

21.0

## Matrix Norm Identities

$||\gamma A|| = |\gamma| \times ||A||$ for any scalar $\gamma$

In [5]:
 A = np.array([[-2,1,0],[5,9,9],[2,3,-2]])

In [6]:
np.linalg.norm(A,ord=2)

13.75151857513156

In [7]:
np.linalg.norm(2*A,ord=2)

27.50303715026312

$||A+ B|| \leq ||A|| + ||B||$

In [8]:
a = np.random.normal(loc=5, size=9)
A = a.reshape((3, 3))
b = np.random.normal(loc=3, size=9)
B = b.reshape((3, 3))

In [9]:
a_norm = np.linalg.norm(A,ord=2)
b_norm = np.linalg.norm(B,ord=2)
sum_norm = np.linalg.norm(A+B,ord=2)

In [10]:
print(a_norm + b_norm)
print(sum_norm)

26.32920209180274
26.098096773084148


$||AB|| \leq ||A|| \times ||B||$

In [11]:
prod_norm = np.linalg.norm(np.dot(A,B),ord=2)

In [12]:
print(a_norm * b_norm)
print(prod_norm)

161.7150771147119
157.08870582650772


$||Ax|| \leq ||A|| \times ||x||$ for any vector x

In [13]:
x = np.array([[3],[4],[9.2]])

In [14]:
vecProd_norm = np.linalg.norm(np.dot(A,x),ord=2)
x_norm = np.linalg.norm(x,ord=2)

In [15]:
print(a_norm * x_norm)
print(vecProd_norm)

173.49517411632428
151.4709694944202


# Condition Number Identities

In [16]:
np.linalg.cond(A)

29.986374744128916

For identity matrix cond(I) = 1

In [17]:
np.linalg.cond(np.identity(15))

1.0

For any matrix $A$ and scalar $\gamma$, cond($\gamma A$) = cond(A)

In [18]:
print(np.linalg.cond(A*5))
print(np.linalg.cond(A*15))

29.986374744128828
29.986374744128895


For any diagonal matrix $D = diag(d_i)$, cond(D) = $\frac{max|d_i|}{min|d_i|}$

In [19]:
D = np.array([[3,0,0,0],[0,6,0,0],[0,0,2,0],[0,0,0,-2]])

In [20]:
np.linalg.cond(D)

3.0

# Gaussian Elemintation

### Assuming matrices are in the traingular form

In [21]:
def gaussElem_lower(A, b):
    """
    Given lower triangular matrix, solves the system of equations
    """
    
    n = len(b)
    x = [None]* n
    for j in range(n):
        if A[j,j] == 0:
            print('Matrix provided is singular')
            break
        x[j] = b[j]/A[j,j]
        for i in range(j+1, n):
            b[i] = b[i] - A[i,j]*x[j]
    return(x)
            
    
    
    

In [22]:
A = np.array([[4,0,0],[1,1,0],[-2,4,2]])
c = [8,4,2]

In [23]:
gaussElem_lower(A, c)

[2.0, 2.0, -1.0]

In [24]:
A = np.array([[4,0,0],[1,0,0],[-2,4,2]])
c = [8,4,2]
gaussElem_lower(A, c)

Matrix provided is singular


[2.0, None, None]

In [25]:
A.shape[1]

3

In [26]:
class SystemSolver():
    def __init__(self,data = []):
        # constructor - empty array
        self.data = data

    
    def LUFactorization(self, A):
        nrows = A.shape[0]
        ncols = A.shape[1]
        n = nrows
        if nrows == ncols:
            L = np.identity(n)
            U = A
            for i in range(n-1):
                for j in range(i+1,n):
                    L[j, i] = U[j,i]/float(U[i,i])
                    U[j,i:n] = U[j,i:n] - (float(L[j,i]) * U[i,i:n])
        return(L,U)
            
        
    def systemSolve(self, A, b):
        L,U = self.LUFactorization(A)
        
        # Forward substitution with L
        n = len(b)
        c = [None]* n
        for j in range(n):
            c[j] = b[j]/float(L[j,j])
            #print(c[j])
            for i in range(j+1, n):
                b[i] = b[i] - L[i,j]*c[j]

                
        # Backward substitution with U 
        x = [None]* n
        for j in range(n-1,-1,-1):
            x[j] = c[j]/float(U[j,j])
            for i in range(j):
                c[i] = c[i] - U[i,j]*x[j]
                
        return(x)
                
            
            
        
        


In [27]:
SS = SystemSolver()
A = np.array([[7,6,10],[3,8,7],[3,5,5]])
A = A.astype(float)
vec = [-7,-3,-2]
SS.systemSolve(A,vec)

[1.0, 1.0, -2.0]

In [28]:
L,U = SS.LUFactorization(A)

In [29]:
SS.systemSolve(U,[-7.0, 0.0, 1.0])

[1.0, 1.0, -2.0]

In [30]:
A = np.array([[7,6,10],[3,8,7],[3,5,5]])
vec = [-7,-3,-2]
A = A.astype(float)
SS.LUFactorization(A)

(array([[1.        , 0.        , 0.        ],
        [0.42857143, 1.        , 0.        ],
        [0.42857143, 0.44736842, 1.        ]]),
 array([[ 7.        ,  6.        , 10.        ],
        [ 0.        ,  5.42857143,  2.71428571],
        [ 0.        ,  0.        , -0.5       ]]))

In [31]:
SS.systemSolve(A,vec)

[-4.526315789473684, -2.5526315789473686, 4.0]

In [32]:
SS = SystemSolver()
A = np.array([[2,1,-2,3],[3,0,4,-2],[2,-1,1,5],[5,2,3,1]])
A = A.astype(float)
vec = [7,-1,13,5]
SS.systemSolve(A,vec)

[1.0, -1.0, -0.0, 2.0]